components:
  schemas:
    AppError:
      properties:
        code:
          format: int32
          type: integer
        message:
          type: string
        reason:
          type: string
      type: object
    ConnectedOuterService:
      properties:
        name:
          type: string
        version:
          type: string
      type: object
    RetrievalInstructionsRequest:
      properties:
        datasetRegistryIds:
          items:
            type: string
          type: array
      type: object
    VersionInfo:
      properties:
        artifactId:
          type: string
        branch:
          type: string
        buildTime:
          type: string
        commitId:
          type: string
        commitMessage:
          type: string
        connectedOuterServices:
          items:
            $ref: '#/components/schemas/ConnectedOuterService'
          type: array
        groupId:
          type: string
        version:
          type: string
      type: object
  securitySchemes:
    Authorization:
      bearerFormat: Authorization
      scheme: bearer
      type: http
info:
  contact:
    email: dps@OSDU.org
    name: OSDU Data Platform Team
  description: Service that enables/facilitates the retrieval of third-party datasets
  license:
    name: Apache 2.0
    url: https://www.apache.org/licenses/LICENSE-2.0.html
  title: External Data Sources Data Management Service APIs
  version: 2.0.0
openapi: 3.0.1
paths:
  /health/liveness_check:
    get:
      description: For deployment available public `/liveness_check` endpoint, which
        provides `External Data Sources Data Management Service is alive` message.
      operationId: livenessCheck
      parameters:
      - description: The file type/format of the request body
        in: header
        name: Content-Type
        required: true
        schema:
          type: string
      - description: Tenant Id
        in: header
        name: data-partition-id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: External Data Sources Data Management Service is alive
      summary: Liveness Check endpoint
      tags:
      - health-check-api
  /health/readiness_check:
    get:
      description: For deployment available public `/readiness_check` endpoint, which
        provides `External Data Sources Data Management Service is ready` message.
      operationId: readinessCheck
      parameters:
      - description: The file type/format of the request body
        in: header
        name: Content-Type
        required: true
        schema:
          type: string
      - description: Tenant Id
        in: header
        name: data-partition-id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            '*/*':
              schema:
                type: string
          description: External Data Sources Data Management Service
      summary: Readiness Check endpoint
      tags:
      - health-check-api
  /info:
    get:
      description: For deployment available public `/info` endpoint, which provides
        build and git related information.
      operationId: info
      parameters:
      - description: The file type/format of the request body
        in: header
        name: Content-Type
        required: true
        schema:
          type: string
      - description: Tenant Id
        in: header
        name: data-partition-id
        required: true
        schema:
          type: string
      responses:
        '200':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/VersionInfo'
          description: Version info.
      summary: info
      tags:
      - info-api
  /retrievalInstructions:
    post:
      description: 'The API returns a list of external retrieval instructions from
        external dataset service/wrapper Allowed roles: service.eds.user.'
      operationId: getRetrievalInstructions
      parameters:
      - description: The file type/format of the request body
        in: header
        name: Content-Type
        required: true
        schema:
          type: string
      - description: Tenant Id
        in: header
        name: data-partition-id
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/RetrievalInstructionsRequest'
        required: true
      responses:
        '200':
          content:
            application/json:
              schema:
                type: string
          description: All kinds retrieved successfully
        '400':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'
          description: Invalid entity format
        '401':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'
          description: Unauthorized
        '403':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'
          description: User not authorized to perform the action.
        '404':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'
          description: Not found
        '500':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'
          description: Internal Server Error
        '502':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'
          description: Bad Gateway
        '503':
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/AppError'
          description: Service Unavailable
      security:
      - Authorization: []
      summary: Get Retrieval Instructions
      tags:
      - eds-dms-api
security:
- Authorization: []
servers:
- url: /api/eds/v1/
tags:
- description: Version info endpoint
  name: info-api
- description: Health Check API
  name: health-check-api
- description: EdsDms related endpoints
  name: eds-dms-api
